name: Tron 🇧🇬
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
     - uses: actions/setup-node@v3
       with:
         node-version: 20
     - name: Checkout
       uses: actions/checkout@v3
     - name: Cache
       id: cache-npm
       uses: actions/cache@v3
       env:
         cache-name: cache-pupp
       with:
         path: ~/.npm
         key: ${{ runner.os }}-pupp-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
         restore-keys: |
           ${{ runner.os }}-pupp-${{ env.cache-name }}-
           ${{ runner.os }}-pupp-
           ${{ runner.os }}-
     - name: 😳 Build
       run: |
          url="https://db.kloun.lol/worker/_design/newsbg/_view/cronews?limit=100"
          response=$(curl -s "$url")
          length=${#response}
          if [[ $length -gt 200 ]]; then
            echo "Output length is greater than 50 characters"
            npm install puppeteer nano jsdom async sanitize-html postgres
            cd ./.github/crons/trans
            node ./server.mjs
          else
            echo "Output length is less than or equal to 50 characters"
          fi
     